[features]
seeds = false
skip-lint = false
resolution = true
anchor-debug = false

[programs.localnet]
stratoshub_marketplace = "StratosHub11111111111111111111111111111111"
stratoshub_escrow = "StratosEscrow111111111111111111111111111111"
stratoshub_registry = "StratosRegistry11111111111111111111111111111"
stratoshub_governance = "StratosDAO1111111111111111111111111111111"

[programs.devnet]
stratoshub_marketplace = "StratosHub11111111111111111111111111111111"
stratoshub_escrow = "StratosEscrow111111111111111111111111111111"
stratoshub_registry = "StratosRegistry11111111111111111111111111111"
stratoshub_governance = "StratosDAO1111111111111111111111111111111"

[programs.mainnet]
stratoshub_marketplace = "StratosHub11111111111111111111111111111111"
stratoshub_escrow = "StratosEscrow111111111111111111111111111111"
stratoshub_registry = "StratosRegistry11111111111111111111111111111"
stratoshub_governance = "StratosDAO1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build && anchor idl parse --file target/idl/stratoshub_marketplace.json --out packages/contracts/src/idl/marketplace.json && anchor idl parse --file target/idl/stratoshub_escrow.json --out packages/contracts/src/idl/escrow.json && anchor idl parse --file target/idl/stratoshub_registry.json --out packages/contracts/src/idl/registry.json && anchor idl parse --file target/idl/stratoshub_governance.json --out packages/contracts/src/idl/governance.json"
deploy-local = "anchor deploy --provider.cluster localnet"
deploy-devnet = "anchor deploy --provider.cluster devnet"
deploy-mainnet = "anchor deploy --provider.cluster mainnet-beta"
upgrade-program = "anchor upgrade --program-id $PROGRAM_ID --provider.cluster $CLUSTER"
verify-build = "anchor verify --provider.cluster $CLUSTER --program-name $PROGRAM_NAME"

[workspace]
members = [
    "programs/marketplace",
    "programs/escrow", 
    "programs/registry",
    "programs/governance"
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
ledger = "test-ledger"
reset = true
skip_preflight = false

[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"

[[test.validator.clone]] 
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.genesis]]
address = "StratosHub11111111111111111111111111111111"
program = "target/deploy/stratoshub_marketplace.so"

[[test.genesis]]
address = "StratosEscrow111111111111111111111111111111"
program = "target/deploy/stratoshub_escrow.so"

[[test.genesis]]
address = "StratosRegistry11111111111111111111111111111"
program = "target/deploy/stratoshub_registry.so"

[[test.genesis]]
address = "StratosDAO1111111111111111111111111111111"
program = "target/deploy/stratoshub_governance.so"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.0"

[build]
docker = false
rust_version = "1.70.0"

[build.env]
RUST_LOG = "error"
ANCHOR_LOG = "error" 